site_name: Brukernotifikasjon-docs

theme:
  name: material
  
  palette:
    primary: grey
    accent: blue
 
  favicon: assets/favicon.ico
 
  logo: assets/nav-icon.svg

extra_css:
  - css/extra.css
